apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-tracer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager-container
        image: potatofields/ray-tracer:manager8
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: secret_access_key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: manager-endpoint
  labels:
    app: manager
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: manager

