apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-tracer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
      - name: tracer-container
        image: potatofields/ray-tracer:rt5
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: secret_access_key
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tracer-endpoint
  labels:
    app: tracer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: tracer

